version: "3.8"
services:
  backend:
    build: ./app
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/
      - DATABASE_NAME=asset_management
    depends_on:
      - mongodb

  frontend:
    build: ./react_app # Updated folder name
    ports:
      - "3000:3000"
    volumes:
      - ./react_app:/app # Updated folder name
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    stdin_open: true
    tty: true
    depends_on:
      - backend

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
